=== 2526rubygv/LMSGI_DTD/DTD/joc_d.dtd
<!ELEMENT joc (titol, companyia, plataforma, anyLlançament, personatges)>

<!ELEMENT personatges (personatge+)>
<!ELEMENT personatge (nom)>
<!ATTLIST personatge tipus CDATA #REQUIRED jugable CDATA #REQUIRED>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT titol (#PCDATA)>
<!ELEMENT companyia (#PCDATA)>
<!ELEMENT plataforma (#PCDATA)>
<!ELEMENT anyLlançament (#PCDATA)>

=== 2526rubygv/LMSGI_DTD/joc_d.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE joc SYSTEM "joc_d.dtd">
<joc>
    <titol>Zelda BOTW</titol>
    <companyia>Nintendo</companyia>
    <plataforma>Nintendo Switch</plataforma>
    <anyLlançament>2017</anyLlançament>

    <personatges>
        <personatge tipus="heroi" jugable="si">
            <nom>Link</nom>
        </personatge>
    </personatges>
</joc>
